package org.firstinspires.ftc.teamcode;

/**
 * Created by vvestin on 10/21/17.
 */

public enum State {
	MOVE
    //COLUMN_COUNTING, STOP, START, TOP_FIELD, BOTTOM_FIELD, BOTTOM_FIELD_DIST, BOTTOM_FIELD_DIST_ADJUST, BOTTOM_FIELD_ADJUST_2, STRAIGHTEN, DELAY, DELAY_LOOP, PUSH_GLYPH_IN, PUSH_GLYPH_IN_RELEASE, PUSH_GLYPH_IN_LOWER, PUSH_GLYPH_IN_ADJUST, START_COLUMN_COUNTING, GET_DISTANCE, GET_DISTANCE_LOOP, BACK_OFF_GLYPH, SENSE_JEWEL, KNOCK_JEWEL_FORWARD, KNOCK_JEWEL_BACKWARD
}